version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gdplus-db  # Asegúrate de que este nombre sea único
    environment:
      MYSQL_ROOT_PASSWORD: tpa20190387
      MYSQL_DATABASE: djlkaosw_gdplus
      MYSQL_USER: djlkaosw_eperea
      MYSQL_PASSWORD: tpa20190387
    volumes:
      - gdplus-db-data:/var/lib/mysql
    ports:
      - "3306:3306"  # El puerto 3306 se usa para MySQL; si es necesario, cámbialo
    networks:
      - gdplus-net

  php-apache:
    image: php:8.1-apache
    container_name: gdplus-php-apache  # Asegúrate de que este nombre sea único
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"  # Cambia el puerto del host si ya está en uso (puedes usar 8080, por ejemplo)
    networks:
      - gdplus-net
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

networks:
  gdplus-net:
    driver: bridge

volumes:
  gdplus-db-data:
