services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "tpa20190387"
      MYSQL_DATABASE: "djlkaosw_gdplus"
      MYSQL_USER: "djlkaosw_eperea"
      MYSQL_PASSWORD: "tpa20190387"
    volumes:
      - gdplus-db-data:/var/lib/mysql
    ports:
      - "3309:3306"  # Cambia este puerto si está en uso
    networks:
      - gdplus-net

  php-apache:
    image: php:8.1-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8088:80"  # Cambia este puerto si está en uso
    networks:
      - gdplus-net
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

networks:
  gdplus-net:
    driver: bridge

volumes:
  gdplus-db-data:
