services:
  php-apache:
    image: php:8.1-apache
    container_name: gdplus_php_apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_HOST=prueba_gdplus_db
      - MYSQL_DATABASE=djlkaosw_gdplus
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
    depends_on:
      - db
    networks:
      - gdplus_network

  db:
    image: mysql:5.7
    container_name: gdplus_db
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=djlkaosw_gdplus
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
    volumes:
      - gdplus_db_data:/var/lib/mysql
    networks:
      - gdplus_network

networks:
  gdplus_network:
    driver: bridge

volumes:
  gdplus_db_data:
    driver: local
